<a href="https://colab.research.google.com/github/markoBel3/Generative-Chatbot-TransformerArchitecture/blob/main/zavrsniFOI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install contractions
import contractions
import nltk
nltk.download('punkt')
import string
import re
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.text import Tokenizer
import tensorflow as tf
import numpy as np
import time

     |████████████████████████████████| 321 kB 9.6 MB/s 
     |████████████████████████████████| 283 kB 27.2 MB/s 
  Created wheel for pyahocorasick: filename=pyahocorasick-1.4.2-cp37-cp37m-linux_x86_64.whl size=85444 sha256=923648ac34e17cd6616d937ff32642ff6aeeac6e7f4e99ec60c8bf892215c77b
  Stored in directory: /root/.cache/pip/wheels/25/19/a6/8f363d9939162782bb8439d886469756271abc01f76fbd790f
Successfully built pyahocorasick
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


Dataset source: https://www.cs.cornell.edu/~cristian/Cornell_Movie-Dialogs_Corpus.html

In [ ]:
import pandas as pd
data = pd.read_csv("/content/drive/MyDrive/Cornel-Question&Answers.csv")
pd.set_option('display.max_colwidth', None)
data.head()

question                                                                     answer
0  Can we make this quick?  Roxanne Korrine and Andrew Barrett are having an incredibly horrendous public break- up on the quad.  Again.    Well, I thought we'd start with pronunciation, if that's okay with you.
1                                                                Well, I thought we'd start with pronunciation, if that's okay with you.                    Not the hacking and gagging and spitting part.  Please.
2                                                                                Not the hacking and gagging and spitting part.  Please.  Okay... then how 'bout we try out some French cuisine.  Saturday?  Night?
3                                                                         You're asking me out.  That's so cute. What's your name again?                                                                 Forget it.
4                                                                      No, no, it's my fault -- we didn't have a proper introduction ---                                                                   Cameron.

In [ ]:
#data['expanded_question'] = data['question'].apply(lambda x: [contractions.fix(word) for word in str(x).split()])
data['question_tokenized'] = data['question'].apply(lambda x: [contractions.fix(word) for word in str(x).split()])
data['answer_tokenized'] = data['answer'].apply(lambda x: [contractions.fix(word) for word in str(x).split()])
data.head()

question  ...                                                                           answer_tokenized
0  Can we make this quick?  Roxanne Korrine and Andrew Barrett are having an incredibly horrendous public break- up on the quad.  Again.  ...  [Well,, I, thought, we would, start, with, pronunciation,, if, that is, okay, with, you.]
1                                                                Well, I thought we'd start with pronunciation, if that's okay with you.  ...                           [Not, the, hacking, and, gagging, and, spitting, part., Please.]
2                                                                                Not the hacking and gagging and spitting part.  Please.  ...       [Okay..., then, how, 'bout, we, try, out, some, French, cuisine., Saturday?, Night?]
3                                                                         You're asking me out.  That's so cute. What's your name again?  ...                                                                              [Forget, it.]
4                                                                      No, no, it's my fault -- we didn't have a proper introduction ---  ...                                                                                 [Cameron.]

[5 rows x 4 columns]

In [ ]:
#data['expanded_question_str'] = [' '.join(map(str, l)) for l in data['expanded_question']]
data['question_tokenized'] = [' '.join(map(str, l)) for l in data['question_tokenized']]
data['answer_tokenized'] = [' '.join(map(str, l)) for l in data['answer_tokenized']]
data.head()

question  ...                                                              answer_tokenized
0  Can we make this quick?  Roxanne Korrine and Andrew Barrett are having an incredibly horrendous public break- up on the quad.  Again.  ...  Well, I thought we would start with pronunciation, if that is okay with you.
1                                                                Well, I thought we'd start with pronunciation, if that's okay with you.  ...                        Not the hacking and gagging and spitting part. Please.
2                                                                                Not the hacking and gagging and spitting part.  Please.  ...       Okay... then how 'bout we try out some French cuisine. Saturday? Night?
3                                                                         You're asking me out.  That's so cute. What's your name again?  ...                                                                    Forget it.
4                                                                      No, no, it's my fault -- we didn't have a proper introduction ---  ...                                                                      Cameron.

[5 rows x 4 columns]

In [ ]:
#data['question_tokenized'] = data['expanded_question_str'].apply(nltk.word_tokenize)
data['question_tokenized'] = data['question_tokenized'].apply(nltk.word_tokenize)
data['answer_tokenized'] = data['answer_tokenized'].apply(nltk.word_tokenize)
data.head()

question  ...                                                                                   answer_tokenized
0  Can we make this quick?  Roxanne Korrine and Andrew Barrett are having an incredibly horrendous public break- up on the quad.  Again.  ...  [Well, ,, I, thought, we, would, start, with, pronunciation, ,, if, that, is, okay, with, you, .]
1                                                                Well, I thought we'd start with pronunciation, if that's okay with you.  ...                               [Not, the, hacking, and, gagging, and, spitting, part, ., Please, .]
2                                                                                Not the hacking and gagging and spitting part.  Please.  ...       [Okay, ..., then, how, 'bout, we, try, out, some, French, cuisine, ., Saturday, ?, Night, ?]
3                                                                         You're asking me out.  That's so cute. What's your name again?  ...                                                                                    [Forget, it, .]
4                                                                      No, no, it's my fault -- we didn't have a proper introduction ---  ...                                                                                       [Cameron, .]

[5 rows x 4 columns]

In [ ]:
#data['question_tokenized'] = data['question_tokenized'].apply(lambda x: [word.lower() for word in x])
data['question_tokenized'] = data['question_tokenized'].apply(lambda x: [word.lower() for word in x])
data['answer_tokenized'] = data['answer_tokenized'].apply(lambda x: [word.lower() for word in x])
data.head()

question  ...                                                                                   answer_tokenized
0  Can we make this quick?  Roxanne Korrine and Andrew Barrett are having an incredibly horrendous public break- up on the quad.  Again.  ...  [well, ,, i, thought, we, would, start, with, pronunciation, ,, if, that, is, okay, with, you, .]
1                                                                Well, I thought we'd start with pronunciation, if that's okay with you.  ...                               [not, the, hacking, and, gagging, and, spitting, part, ., please, .]
2                                                                                Not the hacking and gagging and spitting part.  Please.  ...       [okay, ..., then, how, 'bout, we, try, out, some, french, cuisine, ., saturday, ?, night, ?]
3                                                                         You're asking me out.  That's so cute. What's your name again?  ...                                                                                    [forget, it, .]
4                                                                      No, no, it's my fault -- we didn't have a proper introduction ---  ...                                                                                       [cameron, .]

[5 rows x 4 columns]

In [ ]:
punc = string.punctuation
#data['question_tokenized'] = data['question_tokenized'].apply(lambda x: [word for word in x if word not in punc])
data['question_tokenized'] = data['question_tokenized'].apply(lambda x: [word for word in x if word not in punc])
data.head()

question  ...                                                                                   answer_tokenized
0  Can we make this quick?  Roxanne Korrine and Andrew Barrett are having an incredibly horrendous public break- up on the quad.  Again.  ...  [well, ,, i, thought, we, would, start, with, pronunciation, ,, if, that, is, okay, with, you, .]
1                                                                Well, I thought we'd start with pronunciation, if that's okay with you.  ...                               [not, the, hacking, and, gagging, and, spitting, part, ., please, .]
2                                                                                Not the hacking and gagging and spitting part.  Please.  ...       [okay, ..., then, how, 'bout, we, try, out, some, french, cuisine, ., saturday, ?, night, ?]
3                                                                         You're asking me out.  That's so cute. What's your name again?  ...                                                                                    [forget, it, .]
4                                                                      No, no, it's my fault -- we didn't have a proper introduction ---  ...                                                                                       [cameron, .]

[5 rows x 4 columns]

In [ ]:
def clean(x):
  for i,word in enumerate(x):
    wordNew = re.sub('[\-_,.`"\']', '', word)
    if len(wordNew)<1:
      x.remove(word)
    elif word != wordNew:
      x[i] = wordNew
  return x
#data['question_tokenizedTest'] = data['question_tokenized'].apply(lambda x: clean(x))
data['question_tokenized'].apply(lambda x: clean(x))
data['answer_tokenized'].apply(lambda x: clean(x))
data.head()

question  ...                                                                          answer_tokenized
0  Can we make this quick?  Roxanne Korrine and Andrew Barrett are having an incredibly horrendous public break- up on the quad.  Again.  ...  [well, i, thought, we, would, start, with, pronunciation, if, that, is, okay, with, you]
1                                                                Well, I thought we'd start with pronunciation, if that's okay with you.  ...                            [not, the, hacking, and, gagging, and, spitting, part, please]
2                                                                                Not the hacking and gagging and spitting part.  Please.  ...       [okay, then, how, bout, we, try, out, some, french, cuisine, saturday, ?, night, ?]
3                                                                         You're asking me out.  That's so cute. What's your name again?  ...                                                                              [forget, it]
4                                                                      No, no, it's my fault -- we didn't have a proper introduction ---  ...                                                                                 [cameron]

[5 rows x 4 columns]

In [ ]:
data.head(50)

question  ...                                                                                                                                                                                                                                                    answer_tokenized
0                                                                                        Can we make this quick?  Roxanne Korrine and Andrew Barrett are having an incredibly horrendous public break- up on the quad.  Again.  ...                                                                                                                                                                            [well, i, thought, we, would, start, with, pronunciation, if, that, is, okay, with, you]
1                                                                                                                                                      Well, I thought we'd start with pronunciation, if that's okay with you.  ...                                                                                                                                                                                                      [not, the, hacking, and, gagging, and, spitting, part, please]
2                                                                                                                                                                      Not the hacking and gagging and spitting part.  Please.  ...                                                                                                                                                                                 [okay, then, how, bout, we, try, out, some, french, cuisine, saturday, ?, night, ?]
3                                                                                                                                                               You're asking me out.  That's so cute. What's your name again?  ...                                                                                                                                                                                                                                                        [forget, it]
4                                                                                                                                                            No, no, it's my fault -- we didn't have a proper introduction ---  ...                                                                                                                                                                                                                                                           [cameron]
5                                                                                                                                                                                                                     Cameron.  ...                                                                                                                   [the, thing, is, cameron, i, am, at, the, mercy, of, a, particularly, hideous, breed, of, loser, my, sister, i, can, not, date, until, she, does]
6                                                                                                The thing is, Cameron -- I'm at the mercy of a particularly hideous breed of loser.  My sister.  I can't date until she does.  ...                                                                                                                                                                                                               [seems, like, she, could, get, a, date, easy, enough]
7                                                                                                                                                                                                                         Why?  ...                                                                                   

In [ ]:
word_count = {}
for question in data['question_tokenized']:
    for word in question:
        if word not in word_count:
            word_count[word] = 1
        else:
            word_count[word] += 1
for answer in data['answer_tokenized']:
    for word in answer:
        if word not in word_count:
            word_count[word] = 1
        else:
            word_count[word] += 1
print(len(word_count))
print(word_count)

38040
{'can': 12547, 'we': 20242, 'make': 3249, 'this': 16333, 'quick': 173, 'roxanne': 1, 'korrine': 1, 'and': 31378, 'andrew': 24, 'barrett': 18, 'are': 28294, 'having': 613, 'an': 4595, 'incredibly': 23, 'horrendous': 1, 'public': 206, 'break': 430, 'up': 7775, 'on': 13030, 'the': 67103, 'quad': 2, 'again': 1575, 'well': 7126, 'i': 99103, 'thought': 2041, 'would': 10314, 'start': 865, 'with': 11889, 'pronunciation': 2, 'if': 9057, 'that': 33219, 'is': 57447, 'okay': 2884, 'you': 103232, 'not': 52792, 'hacking': 12, 'gagging': 4, 'spitting': 7, 'part': 676, 'please': 1742, 'asking': 390, 'me': 22234, 'out': 9007, 'so': 9293, 'cute': 157, 'what': 26581, 'your': 14204, 'name': 1674, 'no': 13792, 'it': 45646, 'my': 14270, 'fault': 229, 'did': 10966, 'have': 23549, 'a': 48721, 'proper': 78, 'introduction': 4, 'cameron': 13, 'thing': 2817, 'am': 18018, 'at': 7388, 'mercy': 45, 'of': 27721, 'particularly': 66, 'hideous': 12, 'breed': 20, 'loser': 57, 'sister': 381, 'date': 264, 'until': 73

In [ ]:
threshold= 5
words_indexed = {}
word_number = 4

tokens = ['<PAD>', '<OUT>', '<SOS>', '<EOS>']
for token in tokens:
    words_indexed[token] = len(words_indexed)

for word, count in word_count.items():
    if count >= threshold:
        words_indexed[word] = word_number
        word_number += 1

print(len(words_indexed))
print(words_indexed)


14007
{'<PAD>': 0, '<OUT>': 1, '<SOS>': 2, '<EOS>': 3, 'can': 4, 'we': 5, 'make': 6, 'this': 7, 'quick': 8, 'and': 9, 'andrew': 10, 'barrett': 11, 'are': 12, 'having': 13, 'an': 14, 'incredibly': 15, 'public': 16, 'break': 17, 'up': 18, 'on': 19, 'the': 20, 'again': 21, 'well': 22, 'i': 23, 'thought': 24, 'would': 25, 'start': 26, 'with': 27, 'if': 28, 'that': 29, 'is': 30, 'okay': 31, 'you': 32, 'not': 33, 'hacking': 34, 'spitting': 35, 'part': 36, 'please': 37, 'asking': 38, 'me': 39, 'out': 40, 'so': 41, 'cute': 42, 'what': 43, 'your': 44, 'name': 45, 'no': 46, 'it': 47, 'my': 48, 'fault': 49, 'did': 50, 'have': 51, 'a': 52, 'proper': 53, 'cameron': 54, 'thing': 55, 'am': 56, 'at': 57, 'mercy': 58, 'of': 59, 'particularly': 60, 'hideous': 61, 'breed': 62, 'loser': 63, 'sister': 64, 'date': 65, 'until': 66, 'she': 67, 'does': 68, 'why': 69, 'unsolved': 70, 'mystery': 71, 'used': 72, 'to': 73, 'be': 74, 'really': 75, 'popular': 76, 'when': 77, 'started': 78, 'high': 79, 'school': 80, 

In [ ]:
for question in data['question_tokenized']:
    question.append('<EOS>')
    question.insert(0,'<SOS>')

for answer in data['answer_tokenized']:
    answer.append('<EOS>')
    answer.insert(0,'<SOS>')

In [ ]:
print(data['question_tokenized'])

0                                                                                                                      [<SOS>, can, we, make, this, quick, roxanne, korrine, and, andrew, barrett, are, having, an, incredibly, horrendous, public, break, up, on, the, quad, again, <EOS>]
1                                                                                                                                                                                    [<SOS>, well, i, thought, we, would, start, with, pronunciation, if, that, is, okay, with, you, <EOS>]
2                                                                                                                                                                                                              [<SOS>, not, the, hacking, and, gagging, and, spitting, part, please, <EOS>]
3                                                                                                                                                   

In [ ]:
def convertToInt(inputSen):
    global words_indexed
    sen_into_int = []
    for word in inputSen:
        if word not in words_indexed:
            sen_into_int.append(words_indexed['<OUT>'])
        else:
            sen_into_int.append(words_indexed[word])
    return sen_into_int

data['question_tokenized_int'] = data['question_tokenized'].apply(lambda x: convertToInt(x))
data['answer_tokenized_int'] = data['answer_tokenized'].apply(lambda x: convertToInt(x))

In [ ]:
data.head(50)

question  ...                                                                                                                                                                                                        answer_tokenized_int
0                                                                                        Can we make this quick?  Roxanne Korrine and Andrew Barrett are having an incredibly horrendous public break- up on the quad.  Again.  ...                                                                                                                                                                [2, 22, 23, 24, 5, 25, 26, 27, 1, 28, 29, 30, 31, 27, 32, 3]
1                                                                                                                                                      Well, I thought we'd start with pronunciation, if that's okay with you.  ...                                                                                                                                                                                     [2, 33, 20, 34, 9, 1, 9, 35, 36, 37, 3]
2                                                                                                                                                                      Not the hacking and gagging and spitting part.  Please.  ...                                                                                                                                                  [2, 31, 81, 105, 1627, 5, 914, 40, 502, 398, 1, 222, 13974, 256, 13974, 3]
3                                                                                                                                                               You're asking me out.  That's so cute. What's your name again?  ...                                                                                                                                                                                                             [2, 259, 47, 3]
4                                                                                                                                                            No, no, it's my fault -- we didn't have a proper introduction ---  ...                                                                                                                                                                                                                  [2, 54, 3]
5                                                                                                                                                                                                                     Cameron.  ...                                                                                                                   [2, 20, 55, 30, 54, 23, 56, 57, 20, 58, 59, 52, 60, 61, 62, 59, 63, 48, 64, 23, 4, 33, 65, 66, 67, 68, 3]
6                                                                                                The thing is, Cameron -- I'm at the mercy of a particularly hideous breed of loser.  My sister.  I can't date until she does.  ...                                                                                                                                                                              [2, 411, 84, 67, 91, 136, 52, 65, 919, 302, 3]
7                                                                                                                                                                                                                         Why?  ...                                                                                                                  [2, 70, 71, 67, 72, 73, 74, 75, 76, 77, 67, 78, 79, 80, 81, 47, 82, 83, 84, 67, 85, 86, 59, 47, 87, 88, 3]
8                                                                                        Unsolved mystery.  She used to be really popular when she started high school, then it was ju

In [ ]:
def converToTensor(question,answer):
    # Convert from ragged to dense, padding with zeros.
    question = question.to_tensor()

    #print("first:")
    #print(en)
    #print("second:")
    #print(en)
    # Convert from ragged to dense, padding with zeros.
    #define sentence length(shape=(20,))
    answer = answer.to_tensor()
    #print("third:")
    #print(en)
    return question,answer

In [ ]:
#data[data.columns[0:2]].values
#testingData=tf.ragged.constant(data[data.columns[4:6]].values)
#data

In [ ]:
#print(testingData[0][1])

tf.Tensor([ 2 22 23 24  5 25 26 27  1 28 29 30 31 27 32  3], shape=(16,), dtype=int32)


In [ ]:
#testingOutput=[([2,5,3],[2,4,1]),([2,8,3],[2,4,3])]
#hh=tf.convert_to_tensor(testingOutput)
#print(type(hh[0]))
#testingTensor = tf.ragged.constant(testingOutput)
#print(type(testingTensor))
#print(testingTensor[0])
#datasetNew = tf.data.Dataset.from_tensor_slices(testingTensor)
#for x in testingData:
#  print(x)
#  break
#print(testingData.to_tensor())

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.ops.ragged.ragged_tensor.RaggedTensor'>
<tf.RaggedTensor [[2, 5, 3], [2, 4, 1]]>


In [ ]:
#datasetNew = tf.data.Dataset.from_tensor_slices(testingData)
#tensorData = testingData.to_tensor()
#tensorData
#datasetNew = tf.data.Dataset.from_tensor_slices(tensorData)
#tensorData=tf.expand_dims(tensorData,axis=1)
#tensorData
#for x in tensorData:
  #print(tf.reshape(x, [,]))
  #print(tf.expand_dims(x,axis=0))
 # print(x)
 # break
#datasetNew = tf.reshape(testingData, [,])
#print(testingData.get_shape())

tf.Tensor(
[[ 2  4  5 ...  0  0  0]
 [ 2 22 23 ...  0  0  0]], shape=(2, 511), dtype=int32)


In [ ]:
#print(type(data['question_tokenized_int'].values))
listOfQuestionsNpArray=data['question_tokenized_int'].values
listOfAnswersNpArray=data['answer_tokenized_int'].values
tensorQuestions=tf.ragged.constant(listOfQuestionsNpArray,dtype=tf.int64)
tensorAnswers=tf.ragged.constant(listOfAnswersNpArray,dtype=tf.int64)
datasetNew = tf.data.Dataset.from_tensor_slices((tensorQuestions,tensorAnswers))


In [ ]:
def convertSentenceToTensor(sentence):
  sentence = [contractions.fix(word) for word in str(sentence).split()]
  #print(sentence)
  sentence = ' '.join(map(str, sentence))
  #print(sentence)
  sentence = str(sentence).split()
  #print(sentence)
  sentence = [word.lower() for word in sentence]
  #print(sentence)
  sentence = [word for word in sentence if word not in punc]
  #print(sentence)
  sentence = clean(sentence)
  #print(sentence)
  sentence.append('<EOS>')
  sentence.insert(0,'<SOS>')
  #print(sentence)
  sentence = convertToInt(sentence)
  #print(sentence)
  sentence = tf.convert_to_tensor(sentence, dtype=tf.int64)
  #print(sentence)
  sentence = tf.expand_dims(sentence, 0)
  #print(sentence)
  return sentence

In [ ]:
convertSentenceToTensor("Hi, I'm robot and my name is \"John\" ! ? $")

<tf.Tensor: shape=(1, 11), dtype=int64, numpy=array([[   2,  155,   23,   56, 6977,    9,   48,   45,   30, 2700,    3]])>

In [ ]:
#for x in datasetNew:
#  print(x)
#  break

(<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([ 2,  4,  5,  6,  7,  8,  1,  1,  9, 10, 11, 12, 13, 14, 15,  1, 16,
       17, 18, 19, 20,  1, 21,  3])>, <tf.Tensor: shape=(16,), dtype=int64, numpy=array([ 2, 22, 23, 24,  5, 25, 26, 27,  1, 28, 29, 30, 31, 27, 32,  3])>)


In [ ]:

#datasetNew = tf.data.Dataset.from_tensor_slices(hh)
#print(type(datasetNew))
#for x in datasetNew:
#  print(x)
#  break

<class 'tensorflow.python.data.ops.dataset_ops.TensorSliceDataset'>
tf.Tensor(
[[2 5 3]
 [2 4 1]], shape=(2, 3), dtype=int32)


In [ ]:
BUFFER_SIZE = 20000
BATCH_SIZE = 64

In [ ]:
def make_batches(ds):
  return (
      ds
      .cache()
      .shuffle(BUFFER_SIZE)
      .batch(BATCH_SIZE)
      .map(converToTensor, num_parallel_calls=tf.data.AUTOTUNE)
      .prefetch(tf.data.AUTOTUNE))


train_batches = make_batches(datasetNew)
#val_batches = make_batches(val_examples)

In [ ]:
for x in train_batches:
  print("outB:")
  print(x)
  break

outB:
(<tf.Tensor: shape=(64, 36), dtype=int64, numpy=
array([[   2,   23,   98, ...,    0,    0,    0],
       [   2,   32,  334, ...,    0,    0,    0],
       [   2, 1814, 2464, ...,    0,    0,    0],
       ...,
       [   2, 6502,   43, ...,    0,    0,    0],
       [   2,   22,    7, ...,    0,    0,    0],
       [   2,   23,  104, ...,    0,    0,    0]])>, <tf.Tensor: shape=(64, 42), dtype=int64, numpy=
array([[   2,   23,  497, ...,    0,    0,    0],
       [   2,   43,   50, ...,    0,    0,    0],
       [   2,  105,   12, ...,    0,    0,    0],
       ...,
       [   2, 1088, 6503, ...,    0,    0,    0],
       [   2,  329,   48, ...,    0,    0,    0],
       [   2,   23,   83, ...,    0,    0,    0]])>)


Transformer architecture source: https://www.tensorflow.org/text/tutorials/transformer

In [ ]:
def get_angles(pos, i, d_model):
  angle_rates = 1 / np.power(10000, (2 * (i//2)) / np.float32(d_model))
  return pos * angle_rates
def positional_encoding(position, d_model):
  angle_rads = get_angles(np.arange(position)[:, np.newaxis],
                          np.arange(d_model)[np.newaxis, :],
                          d_model)

  # apply sin to even indices in the array; 2i
  angle_rads[:, 0::2] = np.sin(angle_rads[:, 0::2])

  # apply cos to odd indices in the array; 2i+1
  angle_rads[:, 1::2] = np.cos(angle_rads[:, 1::2])

  pos_encoding = angle_rads[np.newaxis, ...]

  return tf.cast(pos_encoding, dtype=tf.float32)


In [ ]:
def create_padding_mask(seq):
  seq = tf.cast(tf.math.equal(seq, 0), tf.float32)

  # add extra dimensions to add the padding
  # to the attention logits.
  return seq[:, tf.newaxis, tf.newaxis, :]  # (batch_size, 1, 1, seq_len)
def create_look_ahead_mask(size):
  mask = 1 - tf.linalg.band_part(tf.ones((size, size)), -1, 0)
  return mask  # (seq_len, seq_len)

In [ ]:
def scaled_dot_product_attention(q, k, v, mask):
  """Calculate the attention weights.
  q, k, v must have matching leading dimensions.
  k, v must have matching penultimate dimension, i.e.: seq_len_k = seq_len_v.
  The mask has different shapes depending on its type(padding or look ahead)
  but it must be broadcastable for addition.

  Args:
    q: query shape == (..., seq_len_q, depth)
    k: key shape == (..., seq_len_k, depth)
    v: value shape == (..., seq_len_v, depth_v)
    mask: Float tensor with shape broadcastable
          to (..., seq_len_q, seq_len_k). Defaults to None.

  Returns:
    output, attention_weights
  """

  matmul_qk = tf.matmul(q, k, transpose_b=True)  # (..., seq_len_q, seq_len_k)

  # scale matmul_qk
  dk = tf.cast(tf.shape(k)[-1], tf.float32)
  scaled_attention_logits = matmul_qk / tf.math.sqrt(dk)

  # add the mask to the scaled tensor.
  if mask is not None:
    scaled_attention_logits += (mask * -1e9)

  # softmax is normalized on the last axis (seq_len_k) so that the scores
  # add up to 1.
  attention_weights = tf.nn.softmax(scaled_attention_logits, axis=-1)  # (..., seq_len_q, seq_len_k)

  output = tf.matmul(attention_weights, v)  # (..., seq_len_q, depth_v)

  return output, attention_weights
def print_out(q, k, v):
  temp_out, temp_attn = scaled_dot_product_attention(
      q, k, v, None)
  print('Attention weights are:')
  print(temp_attn)
  print('Output is:')
  print(temp_out)
class MultiHeadAttention(tf.keras.layers.Layer):
  def __init__(self, d_model, num_heads):
    super(MultiHeadAttention, self).__init__()
    self.num_heads = num_heads
    self.d_model = d_model

    assert d_model % self.num_heads == 0

    self.depth = d_model // self.num_heads

    self.wq = tf.keras.layers.Dense(d_model)
    self.wk = tf.keras.layers.Dense(d_model)
    self.wv = tf.keras.layers.Dense(d_model)

    self.dense = tf.keras.layers.Dense(d_model)

  def split_heads(self, x, batch_size):
    """Split the last dimension into (num_heads, depth).
    Transpose the result such that the shape is (batch_size, num_heads, seq_len, depth)
    """
    x = tf.reshape(x, (batch_size, -1, self.num_heads, self.depth))
    return tf.transpose(x, perm=[0, 2, 1, 3])

  def call(self, v, k, q, mask):
    batch_size = tf.shape(q)[0]

    q = self.wq(q)  # (batch_size, seq_len, d_model)
    k = self.wk(k)  # (batch_size, seq_len, d_model)
    v = self.wv(v)  # (batch_size, seq_len, d_model)

    q = self.split_heads(q, batch_size)  # (batch_size, num_heads, seq_len_q, depth)
    k = self.split_heads(k, batch_size)  # (batch_size, num_heads, seq_len_k, depth)
    v = self.split_heads(v, batch_size)  # (batch_size, num_heads, seq_len_v, depth)

    # scaled_attention.shape == (batch_size, num_heads, seq_len_q, depth)
    # attention_weights.shape == (batch_size, num_heads, seq_len_q, seq_len_k)
    scaled_attention, attention_weights = scaled_dot_product_attention(
        q, k, v, mask)

    scaled_attention = tf.transpose(scaled_attention, perm=[0, 2, 1, 3])  # (batch_size, seq_len_q, num_heads, depth)

    concat_attention = tf.reshape(scaled_attention,
                                  (batch_size, -1, self.d_model))  # (batch_size, seq_len_q, d_model)

    output = self.dense(concat_attention)  # (batch_size, seq_len_q, d_model)

    return output, attention_weights

In [ ]:
def point_wise_feed_forward_network(d_model, dff):
  return tf.keras.Sequential([
      tf.keras.layers.Dense(dff, activation='relu'),  # (batch_size, seq_len, dff)
      tf.keras.layers.Dense(d_model)  # (batch_size, seq_len, d_model)
  ])

In [ ]:
class EncoderLayer(tf.keras.layers.Layer):
  def __init__(self, d_model, num_heads, dff, rate=0.1):
    super(EncoderLayer, self).__init__()

    self.mha = MultiHeadAttention(d_model, num_heads)
    self.ffn = point_wise_feed_forward_network(d_model, dff)

    self.layernorm1 = tf.keras.layers.LayerNormalization(epsilon=1e-6)
    self.layernorm2 = tf.keras.layers.LayerNormalization(epsilon=1e-6)

    self.dropout1 = tf.keras.layers.Dropout(rate)
    self.dropout2 = tf.keras.layers.Dropout(rate)

  def call(self, x, training, mask):

    attn_output, _ = self.mha(x, x, x, mask)  # (batch_size, input_seq_len, d_model)
    attn_output = self.dropout1(attn_output, training=training)
    out1 = self.layernorm1(x + attn_output)  # (batch_size, input_seq_len, d_model)

    ffn_output = self.ffn(out1)  # (batch_size, input_seq_len, d_model)
    ffn_output = self.dropout2(ffn_output, training=training)
    out2 = self.layernorm2(out1 + ffn_output)  # (batch_size, input_seq_len, d_model)

    return out2
class DecoderLayer(tf.keras.layers.Layer):
  def __init__(self, d_model, num_heads, dff, rate=0.1):
    super(DecoderLayer, self).__init__()

    self.mha1 = MultiHeadAttention(d_model, num_heads)
    self.mha2 = MultiHeadAttention(d_model, num_heads)

    self.ffn = point_wise_feed_forward_network(d_model, dff)

    self.layernorm1 = tf.keras.layers.LayerNormalization(epsilon=1e-6)
    self.layernorm2 = tf.keras.layers.LayerNormalization(epsilon=1e-6)
    self.layernorm3 = tf.keras.layers.LayerNormalization(epsilon=1e-6)

    self.dropout1 = tf.keras.layers.Dropout(rate)
    self.dropout2 = tf.keras.layers.Dropout(rate)
    self.dropout3 = tf.keras.layers.Dropout(rate)

  def call(self, x, enc_output, training,
           look_ahead_mask, padding_mask):
    # enc_output.shape == (batch_size, input_seq_len, d_model)

    attn1, attn_weights_block1 = self.mha1(x, x, x, look_ahead_mask)  # (batch_size, target_seq_len, d_model)
    attn1 = self.dropout1(attn1, training=training)
    out1 = self.layernorm1(attn1 + x)

    attn2, attn_weights_block2 = self.mha2(
        enc_output, enc_output, out1, padding_mask)  # (batch_size, target_seq_len, d_model)
    attn2 = self.dropout2(attn2, training=training)
    out2 = self.layernorm2(attn2 + out1)  # (batch_size, target_seq_len, d_model)

    ffn_output = self.ffn(out2)  # (batch_size, target_seq_len, d_model)
    ffn_output = self.dropout3(ffn_output, training=training)
    out3 = self.layernorm3(ffn_output + out2)  # (batch_size, target_seq_len, d_model)

    return out3, attn_weights_block1, attn_weights_block2

In [ ]:
class Encoder(tf.keras.layers.Layer):
  def __init__(self, num_layers, d_model, num_heads, dff, input_vocab_size,
               maximum_position_encoding, rate=0.1):
    super(Encoder, self).__init__()

    self.d_model = d_model
    self.num_layers = num_layers

    self.embedding = tf.keras.layers.Embedding(input_vocab_size, d_model)
    self.pos_encoding = positional_encoding(maximum_position_encoding,
                                            self.d_model)

    self.enc_layers = [EncoderLayer(d_model, num_heads, dff, rate)
                       for _ in range(num_layers)]

    self.dropout = tf.keras.layers.Dropout(rate)

  def call(self, x, training, mask):

    seq_len = tf.shape(x)[1]

    # adding embedding and position encoding.
    x = self.embedding(x)  # (batch_size, input_seq_len, d_model)
    x *= tf.math.sqrt(tf.cast(self.d_model, tf.float32))
    x += self.pos_encoding[:, :seq_len, :]

    x = self.dropout(x, training=training)

    for i in range(self.num_layers):
      x = self.enc_layers[i](x, training, mask)

    return x  # (batch_size, input_seq_len, d_model)
class Decoder(tf.keras.layers.Layer):
  def __init__(self, num_layers, d_model, num_heads, dff, target_vocab_size,
               maximum_position_encoding, rate=0.1):
    super(Decoder, self).__init__()

    self.d_model = d_model
    self.num_layers = num_layers

    self.embedding = tf.keras.layers.Embedding(target_vocab_size, d_model)
    self.pos_encoding = positional_encoding(maximum_position_encoding, d_model)

    self.dec_layers = [DecoderLayer(d_model, num_heads, dff, rate)
                       for _ in range(num_layers)]
    self.dropout = tf.keras.layers.Dropout(rate)

  def call(self, x, enc_output, training,
           look_ahead_mask, padding_mask):

    seq_len = tf.shape(x)[1]
    attention_weights = {}

    x = self.embedding(x)  # (batch_size, target_seq_len, d_model)
    x *= tf.math.sqrt(tf.cast(self.d_model, tf.float32))
    x += self.pos_encoding[:, :seq_len, :]

    x = self.dropout(x, training=training)

    for i in range(self.num_layers):
      x, block1, block2 = self.dec_layers[i](x, enc_output, training,
                                             look_ahead_mask, padding_mask)

      attention_weights[f'decoder_layer{i+1}_block1'] = block1
      attention_weights[f'decoder_layer{i+1}_block2'] = block2

    # x.shape == (batch_size, target_seq_len, d_model)
    return x, attention_weights

In [ ]:
class Transformer(tf.keras.Model):
  def __init__(self, num_layers, d_model, num_heads, dff, input_vocab_size,
               target_vocab_size, pe_input, pe_target, rate=0.1):
    super(Transformer, self).__init__()

    self.encoder = Encoder(num_layers, d_model, num_heads, dff,
                             input_vocab_size, pe_input, rate)

    self.decoder = Decoder(num_layers, d_model, num_heads, dff,
                           target_vocab_size, pe_target, rate)

    self.final_layer = tf.keras.layers.Dense(target_vocab_size)

  def call(self, inp, tar, training, enc_padding_mask,
           look_ahead_mask, dec_padding_mask):

    enc_output = self.encoder(inp, training, enc_padding_mask)  # (batch_size, inp_seq_len, d_model)

    # dec_output.shape == (batch_size, tar_seq_len, d_model)
    dec_output, attention_weights = self.decoder(
        tar, enc_output, training, look_ahead_mask, dec_padding_mask)

    final_output = self.final_layer(dec_output)  # (batch_size, tar_seq_len, target_vocab_size)

    return final_output, attention_weights

In [ ]:
num_layers = 4
d_model = 128
dff = 512
num_heads = 8
dropout_rate = 0.1

In [ ]:
class CustomSchedule(tf.keras.optimizers.schedules.LearningRateSchedule):
  def __init__(self, d_model, warmup_steps=4000):
    super(CustomSchedule, self).__init__()

    self.d_model = d_model
    self.d_model = tf.cast(self.d_model, tf.float32)

    self.warmup_steps = warmup_steps

  def __call__(self, step):
    arg1 = tf.math.rsqrt(step)
    arg2 = step * (self.warmup_steps ** -1.5)

    return tf.math.rsqrt(self.d_model) * tf.math.minimum(arg1, arg2)

In [ ]:
learning_rate = CustomSchedule(d_model)

optimizer = tf.keras.optimizers.Adam(learning_rate, beta_1=0.9, beta_2=0.98,
                                     epsilon=1e-9)

In [ ]:
loss_object = tf.keras.losses.SparseCategoricalCrossentropy(
    from_logits=True, reduction='none')

In [ ]:
def loss_function(real, pred):
  mask = tf.math.logical_not(tf.math.equal(real, 0))
  loss_ = loss_object(real, pred)

  mask = tf.cast(mask, dtype=loss_.dtype)
  loss_ *= mask

  return tf.reduce_sum(loss_)/tf.reduce_sum(mask)


def accuracy_function(real, pred):
  accuracies = tf.equal(real, tf.argmax(pred, axis=2))

  mask = tf.math.logical_not(tf.math.equal(real, 0))
  accuracies = tf.math.logical_and(mask, accuracies)

  accuracies = tf.cast(accuracies, dtype=tf.float32)
  mask = tf.cast(mask, dtype=tf.float32)
  return tf.reduce_sum(accuracies)/tf.reduce_sum(mask)

In [ ]:
train_loss = tf.keras.metrics.Mean(name='train_loss')
train_accuracy = tf.keras.metrics.Mean(name='train_accuracy')

In [ ]:
transformer = Transformer(
    num_layers=num_layers,
    d_model=d_model,
    num_heads=num_heads,
    dff=dff,
    input_vocab_size=14007,
    target_vocab_size=14007,
    pe_input=1000,
    pe_target=1000,
    rate=dropout_rate)

In [ ]:
def create_masks(inp, tar):
  # Encoder padding mask
  enc_padding_mask = create_padding_mask(inp)

  # Used in the 2nd attention block in the decoder.
  # This padding mask is used to mask the encoder outputs.
  dec_padding_mask = create_padding_mask(inp)

  # Used in the 1st attention block in the decoder.
  # It is used to pad and mask future tokens in the input received by
  # the decoder.
  look_ahead_mask = create_look_ahead_mask(tf.shape(tar)[1])
  dec_target_padding_mask = create_padding_mask(tar)
  combined_mask = tf.maximum(dec_target_padding_mask, look_ahead_mask)

  return enc_padding_mask, combined_mask, dec_padding_mask

In [ ]:
checkpoint_path = "./checkpoints/train"

ckpt = tf.train.Checkpoint(transformer=transformer,
                           optimizer=optimizer)

ckpt_manager = tf.train.CheckpointManager(ckpt, checkpoint_path, max_to_keep=5)

# if a checkpoint exists, restore the latest checkpoint.
if ckpt_manager.latest_checkpoint:
  ckpt.restore(ckpt_manager.latest_checkpoint)
  print('Latest checkpoint restored!!')

In [ ]:
EPOCHS = 2

In [ ]:
# The @tf.function trace-compiles train_step into a TF graph for faster
# execution. The function specializes to the precise shape of the argument
# tensors. To avoid re-tracing due to the variable sequence lengths or variable
# batch sizes (the last batch is smaller), use input_signature to specify
# more generic shapes.

train_step_signature = [
    tf.TensorSpec(shape=(None, None), dtype=tf.int64),#tf.int64
    tf.TensorSpec(shape=(None, None), dtype=tf.int64),
]


@tf.function(input_signature=train_step_signature)
def train_step(inp, tar):
  tar_inp = tar[:, :-1]
  tar_real = tar[:, 1:]

  enc_padding_mask, combined_mask, dec_padding_mask = create_masks(inp, tar_inp)

  with tf.GradientTape() as tape:
    predictions, _ = transformer(inp, tar_inp,
                                 True,
                                 enc_padding_mask,
                                 combined_mask,
                                 dec_padding_mask)
    loss = loss_function(tar_real, predictions)

  gradients = tape.gradient(loss, transformer.trainable_variables)
  optimizer.apply_gradients(zip(gradients, transformer.trainable_variables))

  train_loss(loss)
  train_accuracy(accuracy_function(tar_real, predictions))

In [ ]:
for epoch in range(EPOCHS):
  start = time.time()

  train_loss.reset_states()
  train_accuracy.reset_states()

  # inp -> portuguese, tar -> english
  for (batch, (inp, tar)) in enumerate(train_batches):
    train_step(inp, tar)

    if batch % 50 == 0:
      print(f'Epoch {epoch + 1} Batch {batch} Loss {train_loss.result():.4f} Accuracy {train_accuracy.result():.4f}')

  if (epoch + 1) % 5 == 0:
    ckpt_save_path = ckpt_manager.save()
    print(f'Saving checkpoint for epoch {epoch+1} at {ckpt_save_path}')

  print(f'Epoch {epoch + 1} Loss {train_loss.result():.4f} Accuracy {train_accuracy.result():.4f}')

  print(f'Time taken for 1 epoch: {time.time() - start:.2f} secs\n')

Epoch 1 Batch 0 Loss 9.5443 Accuracy 0.0000
Epoch 1 Batch 50 Loss 9.4912 Accuracy 0.0154
Epoch 1 Batch 100 Loss 9.3974 Accuracy 0.0473
Epoch 1 Batch 150 Loss 9.2669 Accuracy 0.0588
Epoch 1 Batch 200 Loss 9.0966 Accuracy 0.0640
Epoch 1 Batch 250 Loss 8.8888 Accuracy 0.0675
Epoch 1 Batch 300 Loss 8.6487 Accuracy 0.0700
Epoch 1 Batch 350 Loss 8.3948 Accuracy 0.0712
Epoch 1 Batch 400 Loss 8.1419 Accuracy 0.0722
Epoch 1 Batch 450 Loss 7.9120 Accuracy 0.0732
Epoch 1 Batch 500 Loss 7.7124 Accuracy 0.0741
Epoch 1 Batch 550 Loss 7.5452 Accuracy 0.0754
Epoch 1 Batch 600 Loss 7.4005 Accuracy 0.0771
Epoch 1 Batch 650 Loss 7.2689 Accuracy 0.0800
Epoch 1 Batch 700 Loss 7.1479 Accuracy 0.0842
Epoch 1 Batch 750 Loss 7.0348 Accuracy 0.0885
Epoch 1 Batch 800 Loss 6.9312 Accuracy 0.0928
Epoch 1 Batch 850 Loss 6.8385 Accuracy 0.0970
Epoch 1 Batch 900 Loss 6.7520 Accuracy 0.1011
Epoch 1 Batch 950 Loss 6.6739 Accuracy 0.1047
Epoch 1 Batch 1000 Loss 6.5997 Accuracy 0.1081
Epoch 1 Batch 1050 Loss 6.5329 Accur

In [ ]:
def returnTokens():
  start = tf.convert_to_tensor(2, dtype=tf.int64)
  end = tf.convert_to_tensor(3, dtype=tf.int64)
  return start, end

In [ ]:
print(returnTokens()[0])

tf.Tensor(2, shape=(), dtype=int64)


In [ ]:
inv_words_indexed = {value:key for key, value in words_indexed.items()}
def fromIntToWords(output):
  sentence = []
  for number in output[0]:
    #print(inv_words_indexed[number])
    #with tf.Session() as sess:  print(number.eval())
    word = inv_words_indexed[number.numpy()]
    if number.numpy() not in [1,2,3]:
      sentence.append(word)
  sentence = " ".join(sentence)
  return sentence

In [ ]:
fromIntToWords(convertSentenceToTensor("Hi, this is test."))

tf.Tensor([   2  155    7   30 1473    3], shape=(6,), dtype=int64)
hi this is test


In [ ]:
def evaluate(sentence, max_length=40):
  # inp sentence is portuguese, hence adding the start and end token
  sentence = convertSentenceToTensor(sentence)

  encoder_input = sentence

  # as the target is english, the first word to the transformer should be the
  # english start token.
  start, end = returnTokens()
  output = tf.convert_to_tensor([start])
  output = tf.expand_dims(output, 0)

  for i in range(max_length):
    enc_padding_mask, combined_mask, dec_padding_mask = create_masks(
        encoder_input, output)

    # predictions.shape == (batch_size, seq_len, vocab_size)
    predictions, attention_weights = transformer(encoder_input,
                                                 output,
                                                 False,
                                                 enc_padding_mask,
                                                 combined_mask,
                                                 dec_padding_mask)

    # select the last word from the seq_len dimension
    predictions = predictions[:, -1:, :]  # (batch_size, 1, vocab_size)

    predicted_id = tf.argmax(predictions, axis=-1)

    # concatentate the predicted_id to the output which is given to the decoder
    # as its input.
    output = tf.concat([output, predicted_id], axis=-1)
    # return the result if the predicted_id is equal to the end token
    if predicted_id == end:
      break

  # output.shape (1, tokens)
  text = fromIntToWords(output)  # shape: ()
  return text

In [ ]:
def print_translation(sentence, tokens, ground_truth):
  print(f'{"Input:":15s}: {sentence}')
  print(f'{"Prediction":15s}: {tokens}')
  print(f'{"Ground truth":15s}: {ground_truth}')

In [ ]:
sentence = "Just testing"
ground_truth = "This is cool"

translated_text = evaluate(sentence)
print_translation(sentence, translated_text, ground_truth)

i am not going to be a little
Input:         : Just testing
Prediction     : i am not going to be a little
Ground truth   : This is cool
